[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/health"
timeout = 100
interval = 30
